Added functions for working with source archives
- also added support for local configuration (.pk-maint/config)
- stamp command no longer pass its --format string directly to Python

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -26,7 +26,7 @@ EDIT=""
 OUTPUT='vars.cfg'
 
 error() {
-  echo "$0: error: $*" 1>&2
+  echo "$0: error: $*" >&2
   exit 1
 }
 
@@ -87,11 +87,9 @@ assert_bash() {
 }
 
 # File & directory utils
-require touch
 require mkdir
 require cp
 require rm
-require stat
 require ls
 require chmod
 # Text utils
diff --git a/mr-proper b/mr-proper
--- a/mr-proper
+++ b/mr-proper
@@ -16,7 +16,7 @@ last_stderr=""
 verbose=0
 
 error() {
-  echo "$0: error: $*" 1>&2
+  echo "$0: error: $*" >&2
   exit 1
 }
 
@@ -33,7 +33,7 @@ try_run() {
   [ $verbose -ne 0 ] && [ $last_error -eq 0 ] && echo "ok"
 }
 
-while [ "$*" ]; do
+while [ $# -gt 0 ]; do
   case "$1" in
     --help | -h | -\?)
       echo "Usage: $0 [options]"
